files:
  - source: /book/website
    ignore_settings: 1
    ignore:
      - LICENSE.md
      - _toc.yml
      - _config.yml
      - _redirects
      - /requirements.txt
      - runtime.txt
      - figures
      - '*.png'
      - '*.jpg'
      - _build/html
      - _static
      - scripts
      - requirements
      - translation
      - figures
      - assets
      - analytic
      - netlify.toml
      - _bibliography
      - node_modules
      - package.json
      - package-lock.json
    translation: /book/translation/%three_letters_code%/book/website/%original_path%/%original_file_name%
